name: History changelog

on:  
    workflow_dispatch:
     inputs:
      environment:
        description: 'Select the environment'
        type: choice
        options: [TEST, UAT, PROD]
        required: true

jobs:
  History-changelog:
    runs-on: ubuntu-latest
    name: History Action
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'history'
          classpath: 'changelog'
          changeLogFile: 'changelog.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}