name: Update changelog

on:  
    workflow_dispatch:
     inputs:
      changelogfile:
        description: 'Enter changelog file name'
        required: true
      environment:
        description: 'Select the environment'
        type: choice
        options: [TEST, UAT, PROD]
        required: true

jobs:
  Update-liquibase-changelog:
    runs-on: ubuntu-latest
    name: Update Action
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.23.2
        with:
          operation: 'update'
          classpath: 'changelog'
          changeLogFile: 'changelog/${{ github.event.inputs.changelogfile }}'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}