name: Update changelog

on:  
    workflow_dispatch:

jobs:
  Update-liquibase-changelog:
    runs-on: ubuntu-latest
    name: Update Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'changelog'
          changeLogFile: 'changelog.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}